baseurl: ""
url: "https://www.lec-tu-ra.com"

title: Lectura
theme: minima

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: "vision/index.md"
    values:
      permalink: /vision/
